In [ ]:
import pandas as pd

#Load the dataset 
df = pd.read_csv('../data/resale_transactions.csv')

df.head() #to show the first 5 rows of the dataset
df.info() #to show the non-null values and data types of each column
df.isnull().sum() #to show the number of missing values in each column
df.describe().T #to show the summary statistics of the dataset
df.duplicated().sum() #to show the number of duplicate rows in the dataset

<class 'pandas.DataFrame'>
RangeIndex: 88688 entries, 0 to 88687
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   88688 non-null  int64
 1   month                88688 non-null  str
 2   flat_type            88688 non-null  str
 3   block                88688 non-null  str
 4   street_name          88688 non-null  str
 5   storey_range         88688 non-null  str
 6   floor_area_sqm       88688 non-null  float64
 7   lease_commence_date  88688 non-null  int64
 8   remaining_lease      88688 non-null  str
 9   resale_price         88688 non-null  float64
 10  town_id              88688 non-null  int64
 11  flatm_id             88688 non-null  int64
 12  town_name            87905 non-null  str
 13  flatm_name           88174 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 9.5 MB

np.int64(4223)

In [1]:
import pandas as pd

#Load the dataset 
df = pd.read_csv('../data/resale_transactions.csv')

df.head() #to show the first 5 rows of the dataset
df.info() #to show the non-null values and data types of each column
df.isnull().sum() #to show the number of missing values in each column
df.describe().T

<class 'pandas.DataFrame'>
RangeIndex: 88688 entries, 0 to 88687
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   88688 non-null  int64
 1   month                88688 non-null  str
 2   flat_type            88688 non-null  str
 3   block                88688 non-null  str
 4   street_name          88688 non-null  str
 5   storey_range         88688 non-null  str
 6   floor_area_sqm       88688 non-null  float64
 7   lease_commence_date  88688 non-null  int64
 8   remaining_lease      88688 non-null  str
 9   resale_price         88688 non-null  float64
 10  town_id              88688 non-null  int64
 11  flatm_id             88688 non-null  int64
 12  town_name            87905 non-null  str
 13  flatm_name           88174 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 9.5 MB

,count,mean,std,min,25%,50%,75%,max
id,88688.0,42233.303739,24376.312037,1.0,21136.75,42228.5,63339.25,84465.0
floor_area_sqm,88688.0,97.520444,24.197379,31.0,76.00,96.0,112.00,280.0
lease_commence_date,88688.0,1570.225352,1226.315949,-2016.0,1980.00,1988.0,2000.00,2016.0
resale_price,88688.0,438679.303299,146670.254508,160000.0,335000.00,408000.0,505000.00,1200000.0
town_id,88688.0,14.631337,8.032285,1.0,8.00,15.0,22.00,26.0
flatm_id,88688.0,8.889185,3.906898,1.0,5.00,8.0,12.00,21.0

In [ ]:
import pandas as pd

#Load the dataset 
df = pd.read_csv('../data/resale_transactions.csv')

df.duplicated().sum() #to show the number of duplicate rows in the dataset
df[df.duplicated(keep=False)].sort_values(by=list(df.columns)) #to show the duplicate rows in the dataset list all the columns in the dataset
df.drop_duplicates(inplace=True) #to drop the duplicate rows in the dataset

,id,month,flat_type,block,street_name,storey_range,floor_area_sqm,lease_commence_date,remaining_lease,resale_price,town_id,flatm_id,town_name,flatm_name
103,104,2016-09,3 ROOM,201E,TAMPINES ST 23,04 TO 06,68.0,-1987,70,305000.0,23,12,TAMPINES,New Generation
88570,104,2016-09,3 ROOM,201E,TAMPINES ST 23,04 TO 06,68.0,-1987,70,305000.0,23,12,TAMPINES,New Generation
106,107,2015-08,4 ROOM,146,SERANGOON NTH AVE 1,13 TO 15,83.0,-1987,70,355000.0,22,17,SERANGOON,Simplified
88156,107,2015-08,4 ROOM,146,SERANGOON NTH AVE 1,13 TO 15,83.0,-1987,70,355000.0,22,17,SERANGOON,Simplified
114,115,2017-03,4 ROOM,274D,PUNGGOL PL,16 TO 18,93.0,2013,95 years 04 months,560000.0,18,13,PUNGGOL,Premium Apartment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87372,84427,2019-01,5 ROOM,348D,YISHUN AVE 11,13 TO 15,112.0,2013,93 years 09 months,758000.0,26,4,YISHUN,DBSS
84428,84429,2018-10,4 ROOM,838,HOUGANG CTRL,04 TO 06,100.0,-1997,77 years 05 months,530000.0,12,8,HOUGANG,Model A
85835,84429,2018-10,4 ROOM,838,HOUGANG CTRL,04 TO 06,100.0,-1997,77 years 05 months,530000.0,12,8,HOUGANG,Model A
84461,84462,2015-06,5 ROOM,596A,ANG MO KIO ST 52,07 TO 09,110.0,2002,86,760000.0,1,5,ANG MO KIO,Improved
87186,84462,2015-06,5 ROOM,596A,ANG MO KIO ST 52,07 TO 09,110.0,2002,86,760000.0,1,5,ANG MO KIO,Improved

In [ ]:
import pandas as pd

#Load the dataset 
df = pd.read_csv('../data/resale_transactions.csv')
df.drop_duplicates(inplace=True) #to drop the duplicate rows in the dataset
df.duplicated().sum() #to show the number of duplicate rows in the dataset

np.int64(0)